### ISSUE TITLE
DRS is not compatible with BLT making migration not possible

### ISSUE THREAD

**Issue by korkhau** [acquia/drupal-recommended-settings#75]
**Describe the bug**
BLT allowed for configuration overrides; for example, we had `init` disabled:
```yml
disable-targets:
  blt:
    shell-alias:
      init: true
```

**To Reproduce**
1. Install with `composer install`
2. See settings added into `/default/settings.php`
```php
require DRUPAL_ROOT . "/../vendor/acquia/drupal-recommended-settings/settings/acquia-recommended.settings.php";
/**
 * IMPORTANT.
 *
 * Do not include additional settings here. Instead, add them to settings
 * included by `acquia-recommended.settings.php`. See Acquia's documentation for more detail.
 *
 * @link https://docs.acquia.com/
 */
```

**Expected behavior**
By using `/drs/config.yml` we should be able to disable running of `/bin/drush drs:init:settings` on `composer install` as it is in BLT

**Additional context**
`onPostCmdEvent` does not take into account any properties from config at all:
```php
  /**
   * Includes Acquia recommended settings post composer update/install command.
   */
  public function onPostCmdEvent(): void {
    // Only install the template files, if the drupal-recommended-settings
    // plugin is installed, with drupal project.
    if ($this->settingsPackage && $this->getDrupalRoot() && !$this->bltUpdated) {
      $vendor_dir = $this->composer->getConfig()->get('vendor-dir');
      $this->executeCommand(
        $vendor_dir . "/bin/drush drs:init:settings", [],
        TRUE
      );
    }
  }
```

**Comment by vishalkhode1** [comment]
Hi @korkhau
I don't think it's a bug, because this can be already achieve (as of today), but the process it bit different then BLT.

**Approach 1:** If you don't want settings.php command to be generated only during composer install / composer update, then you can go with Option 1 as mentioned in above [comment](https://github.com/acquia/drupal-recommended-settings/issues/75#issuecomment-2501754473).

**Approach 1:** If you don't want settings.php command to be generated in any case or based on your custom use case, then you can create your own composer library or drush-command, and use `PRE_COMMAND_HOOK` hook and write logic to skip settings.php generation on your custom use case. You can see [example](https://github.com/acquia/drupal-recommended-settings/pull/77/files#diff-c4b540e6a4922c7c66174c7f28a50394f1c7bc41fe4ecf76f61d658c95e094d8R42).

Let me know, if you've any concern / query.
Thanks.

**Comment by korkhau** [comment]
@vishalkhode1, thank you for your reply.
The proposed workaround is acceptable, so we can utilize it for sure.
I agree that it is not a blocker for migration, but it is not documented. 
Our assumption is that migration is required, but the steps are also clear.
Could you add proposed options to Acquia documentation?
Thanks
